### ISSUE TITLE
implement context manager

### ISSUE THREAD

**Issue by undera** [bitranox/wrapt_timeout_decorator#19]
Hello,

I've searched through code and issues and did not find a ready answer.

For my purposes, I'd like to use your awesome library as context manager. Like this:
```python
def demo(url, timeout):
    with AwesomeTimeout(timeout):
        requests.get(url)
```

The need comes from variable timeout value. I realize I could create a decorated function each time I'm executing `requests.get()`, but it does not look elegant and makes code less readable and performant.

Can you please point me to existing function I can use, or share a code snippet, or implement this as a new feature?

**Comment by bitranox** [comment]
Dear Undera,
 - read "General Recommendations" I guess You should use urllib3 for Your requests, and there are all sorts of timeouts already. So only use my timeout decorator if absolutely neccessary.
- better find out WHICH part of the request is timing out (nameservice ? or what ? ) and try to resolve it.
- read "use as function not as decorator" - You can do something like : 

```
def demo(url, timeout):
    timeout(dec_timeout=timeout)(requests.get)(url)
    ...
```
but I dont like it very much - why You want to write that every time You use Your get function ?
I would prefer : 

```
# file : settings.py
default_request_timeout = 5
```
```
# file : lib_request.py
import requests from <whatever You use here>
import settings
from wrapt_timeout_decorator import timeout

@timeout(dec_timeout=settings.default_request_timeout)
def get_request(url):
    result = requests.get(url)
    return result
```
```
# file : some module of Your application
import settings
import lib_request 

def demo(url, timeout=settings.default_request_timeout):
    result = lib_request.get_request(url, dec_timeout=timeout)
    ...

# or if You are fine with the default timeout - much cleaner
def demo2(url):
    result = lib_request.get_request(url)
```

But ok - it should not be too hard to implement context manager - I will check how to implement it.
I will take some time since I am busy with smth else.
Robert

**Comment by undera** [comment]
I have read the warnings you put and I take all responsibility on using this lib. I've taken `requests.get` as just an example. Let's say the operation is `sleep` (or my custom app code which is true). I believe this library is not requests- or urllib-specific, and should serve the purpose.

Regarding "use as function" - it makes code even less elegant IMO. The `with` statement is beautiful, because it allows to control the scope of timeout very well.

Thank you for considering to implement this. :+1:

**Comment by undera** [comment]
I tried to wrap it into context manager myself, but timeouts do not get triggered:
```python
def test_timeout(self):
        with timeout(0.01):
            logging.debug("Start request")
            requests.get("https://news.google.com")
            logging.debug("End request")

        logging.debug("All done")


@contextmanager
def timeout(to):
    @wrapt_timeout_decorator.timeout(to)
    def wrapper():
        logging.debug("Wrapper start")
        try:
            yield
        finally:
            pass
        logging.debug("Wrapper done")

    yield from wrapper()

```

**Comment by bitranox** [comment]
Andrey, 
the meaning is - only use the timeout decorator if You have no other choice - because it has some downsides. Only use it for parts of code You dont have control over (some third party library or such).
Regarding "use as function" - it makes code even less elegant - here I disagree.
Since You should not sprincle Your code with timeouts, just use it as a wrapper for the code parts You really need to time out, like shown in the example provided before.
You also have to be aware that You can not use "nested" timeouts with signals, or in threads - 
and if You use use_signals = False, You are forking, what might take a lot of time and memory .... 
So - better avoid it ;-)
Well, it is somehow unusual that the creator of the library says : dont use it. But its true.
Robert

**Comment by undera** [comment]
I found out that this lib works for me, if I use it in my code snipped from above: https://github.com/pnpnpn/timeout-decorator. That lib also is published on PyPi, which is more convenient for me.

I will use that lib for now, 'cause I gotta complete my task.

**Comment by bitranox** [comment]
great ! then use pnpnpn´s decorator ! 
my decorator focus on cases were the pnpnpn can not work ... 
wrapt_timeout_decorator is also published on PyPi, BTW.
