### ISSUE TITLE
Issue if the decorator is used inside uvicorn / fastapi

### ISSUE THREAD

**Issue by alor** [bitranox/wrapt_timeout_decorator#52]
* **I'm submitting a ... **
  - [X] bug report
  - [X] feature request

* **Do you want to request a *feature* or report a *bug*?**

it's a but only if used inside a uvicorn server, but since there is a solution, it is also a feature request to insert the solution in this wrapper.

* **What is the current behavior?**

when the timeout is reached the Uvicorn server shut down itself because it is intercepting the SIGINT sent to the child process.

```
frontend-api-1  | INFO:     Shutting down
frontend-api-1  | INFO:     Waiting for connections to close. (CTRL+C to force quit)
frontend-api-1  | ERROR:  Function long_task timed out after 5.0 seconds
frontend-api-1  | INFO:     192.168.65.1:48555 - "GET /long_task HTTP/1.1" 400 Bad Request
frontend-api-1  | INFO:     Finished server process [1]
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

just wrap a Django method (served by uvicorn) with the @timeout(N) decorator. 
perform some long running operation and wait for the timeout to expire.
the uvicorn server will shut down on timeout

* **What is the expected behavior?**

the uvicorn server should not catch the SIGINT and continue working.

* **Please tell us about your environment:**

- Version of wrapt_timeout_decorator : 
- Python Version :  3.9.x
- OS, OS Version :   OSX, Linux

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

the solution and the root cause is explained here: https://github.com/tiangolo/fastapi/discussions/7442#discussioncomment-5141007

maybe we can insert this code:
```
    signal.set_wakeup_fd(-1)
    signal.signal(signal.SIGTERM, signal.SIG_DFL)
    signal.signal(signal.SIGINT, signal.SIG_DFL)
```

in the `_target` method of wrap_function_multiprocess.py so the child process will restore the original signal handlers without messing with the one inherited from the parent (uvicorn)

what do you think?

**Comment by bitranox** [comment]
Dear Alor,

Good point!

We've released a new version with the `dec_mp_reset_signals` parameter. This addition restores the default behavior of signal handlers when using the `fork` method in multiprocessing, making it particularly suitable for FastAPI and Uvicorn environments.

Please refer to the `readme.rst` for detailed information.

Should you have any questions, feel free to reach out. Additionally, if you're considering whether this method is suitable for FastAPI, it's worth noting that an alternative approach could involve setting a different start method, like `forkserver`. It might be slower but will offer additional process isolation. However, please be aware that we're using `multiprocess` rather than `multiprocessing`.

Looking forward to your feedback!
